### PR TITLE
1.1.0 : implemented hasXss function, compatibility with Laravel 5

### PR DESCRIPTION
**Pull request by fireproofsocks**
This handles issues #11 and #12

### CODE REVIEW

**Comment by janhartigan** [comment]
Thanks for putting this together. Several things to note:
- Backwards-incompatible changes require a new major version.
- The composer.json file should indicate that laravel 5 is required

Once these things are resolved, I merge this in.

**Comment by benjaminkohl** [comment]
Speaking of versions, if you do consider pulling this, please push a tag for v1.0.0 or something before doing that. This is the one remaining package in my project's composer.json that just specifies "dev-master". I'd prefer to replace that with a specific version.

**Comment by scottconnerly** [comment]
+1 for a version tag. @fireproofsocks Can you please make those changes so this can get merged in?

**Comment by fireproofsocks** [comment]
Sorry to be confused here, but what exactly do you need changed?  My git shui is weak.  Do you need a tag added and pushed?

**Comment by janhartigan** [comment]
@fireproofsocks basically just bump the readme to 2.0.0 instead of 1.1.0.

**Comment by fireproofsocks** [comment]
Sorry, I'm not clear on what you mean by bumping the readme.  Could you clarify?  Apropos, I added this: https://github.com/FrozenNode/XssInput/issues/16

**Pull request closed without merging**
